---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-cephfs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-fs
---
apiVersion: v1
kind: Pod
metadata:
  name: test-cephfs-pod
spec:
  containers:
  - name: test-pod
    image: busybox
    command: [ "/bin/sh" ]
    args: [ "-c", "while true; do sleep 3600; done" ]
    volumeMounts:
    - name: cephfs-vol
      mountPath: /mnt/cephfs
  volumes:
  - name: cephfs-vol
    persistentVolumeClaim:
      claimName: test-cephfs
