---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deploy-capmox
  namespace: default
  annotations:
    projectsveltos.io/template: ok
data:
  capmox.yaml: |
    {{- if index (getResource "Users") "data" }}
      {{- range $key, $value := (getResource "Users").data }}
        {{- $user := $value | fromYaml }}
          apiVersion: cluster.x-k8s.io/v1beta1
          kind: Cluster
          metadata:
            name: {{ $key }}
            namespace: default
            labels:
              env: {{ $user.env }}
          spec:
            clusterNetwork:
              pods:
                cidrBlocks:
                - 10.44.0.0/16
            controlPlaneRef:
              apiVersion: controlplane.cluster.x-k8s.io/v1beta1
              kind: KubeadmControlPlane
              name: {{ $key }}-control-plane
            infrastructureRef:
              apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
              kind: ProxmoxCluster
              name: {{ $key }}
    ---
          apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
          kind: ProxmoxCluster
          metadata:
            name: {{ $key }}
            namespace: default
          spec:
            allowedNodes:
            - pve
            controlPlaneEndpoint:
              host: {{ $user.controlplaneendpoint }}
              port: 6443
            dnsServers:
            - {{ $user.gateway }}
            ipv4Config:
              addresses:
              - {{ $user.addresses }}
              gateway: {{ $user.gateway }}
              prefix: 24
            schedulerHints:
              memoryAdjustment: 0
    ---
          apiVersion: controlplane.cluster.x-k8s.io/v1beta1
          kind: KubeadmControlPlane
          metadata:
            name: {{ $key }}-control-plane
            namespace: default
          spec:
            kubeadmConfigSpec:
              files:
              - content: |
                  apiVersion: v1
                  kind: Pod
                  metadata:
                    creationTimestamp: null
                    name: kube-vip
                    namespace: kube-system
                  spec:
                    containers:
                    - args:
                      - manager
                      env:
                      - name: cp_enable
                        value: "true"
                      - name: vip_interface
                        value: ""
                      - name: address
                        value: {{ $user.controlplaneendpoint }}
                      - name: port
                        value: "6443"
                      - name: vip_arp
                        value: "true"
                      - name: vip_leaderelection
                        value: "true"
                      - name: vip_leaseduration
                        value: "15"
                      - name: vip_renewdeadline
                        value: "10"
                      - name: vip_retryperiod
                        value: "2"
                      image: ghcr.io/kube-vip/kube-vip:v0.7.1
                      imagePullPolicy: IfNotPresent
                      name: kube-vip
                      resources: {}
                      securityContext:
                        capabilities:
                          add:
                          - NET_ADMIN
                          - NET_RAW
                      volumeMounts:
                      - mountPath: /etc/kubernetes/admin.conf
                        name: kubeconfig
                    hostAliases:
                    - hostnames:
                      - localhost
                      - kubernetes
                      ip: 127.0.0.1
                    hostNetwork: true
                    volumes:
                    - hostPath:
                        path: /etc/kubernetes/admin.conf
                        type: FileOrCreate
                      name: kubeconfig
                  status: {}
                owner: root:root
                path: /etc/kubernetes/manifests/kube-vip.yaml
              - content: |
                  #!/bin/bash

                  # Copyright 2020 The Kubernetes Authors.
                  #
                  # Licensed under the Apache License, Version 2.0 (the "License");
                  # you may not use this file except in compliance with the License.
                  # You may obtain a copy of the License at
                  #
                  #     http://www.apache.org/licenses/LICENSE-2.0
                  #
                  # Unless required by applicable law or agreed to in writing, software
                  # distributed under the License is distributed on an "AS IS" BASIS,
                  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
                  # See the License for the specific language governing permissions and
                  # limitations under the License.

                  set -e

                  # Configure the workaround required for kubeadm init with kube-vip:
                  # xref: https://github.com/kube-vip/kube-vip/issues/684

                  # Nothing to do for kubernetes < v1.29
                  KUBEADM_MINOR="$(kubeadm version -o short | cut -d '.' -f 2)"
                  if [[ "$KUBEADM_MINOR" -lt "29" ]]; then
                    exit 0
                  fi

                  IS_KUBEADM_INIT="false"

                  # cloud-init kubeadm init
                  if [[ -f /run/kubeadm/kubeadm.yaml ]]; then
                    IS_KUBEADM_INIT="true"
                  fi

                  # ignition kubeadm init
                  if [[ -f /etc/kubeadm.sh ]] && grep -q -e "kubeadm init" /etc/kubeadm.sh; then
                    IS_KUBEADM_INIT="true"
                  fi

                  if [[ "$IS_KUBEADM_INIT" == "true" ]]; then
                    sed -i 's#path: /etc/kubernetes/admin.conf#path: /etc/kubernetes/super-admin.conf#' \
                      /etc/kubernetes/manifests/kube-vip.yaml
                  fi
                owner: root:root
                path: /etc/kube-vip-prepare.sh
                permissions: "0700"
              initConfiguration:
                nodeRegistration:
                  kubeletExtraArgs:
                    provider-id: proxmox://'{{`{{ ds.meta_data.instance_id }}`}}'
              joinConfiguration:
                nodeRegistration:
                  kubeletExtraArgs:
                    provider-id: proxmox://'{{`{{ ds.meta_data.instance_id }}`}}'
              preKubeadmCommands:
              - /etc/kube-vip-prepare.sh
              users:
              - name: root
                sshAuthorizedKeys:
                - ssh-ed25519 AAAAC
            machineTemplate:
              infrastructureRef:
                apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
                kind: ProxmoxMachineTemplate
                name: {{ $key }}-control-plane
            replicas: 1
            version: v1.33.3
    ---
          apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
          kind: ProxmoxMachineTemplate
          metadata:
            name: {{ $key }}-control-plane
            namespace: default
          spec:
            template:
              spec:
                disks:
                  bootVolume:
                    disk: scsi0
                    sizeGb: 20
                format: qcow2
                full: true
                memoryMiB: 4096
                network:
                  default:
                    bridge: vmbr2
                    model: virtio
                numCores: 4
                numSockets: 1
                sourceNode: pve
                templateID: 104
    ---
          apiVersion: cluster.x-k8s.io/v1beta1
          kind: MachineDeployment
          metadata:
            name: {{ $key }}-workers
            namespace: default
          spec:
            clusterName: {{ $key }}
            replicas: 1
            selector:
              matchLabels: null
            template:
              metadata:
                labels:
                  node-role.kubernetes.io/node: ""
              spec:
                bootstrap:
                  configRef:
                    apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
                    kind: KubeadmConfigTemplate
                    name: {{ $key }}-worker
                clusterName: {{ $key }}
                infrastructureRef:
                  apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
                  kind: ProxmoxMachineTemplate
                  name: {{ $key }}-worker
                version: v1.33.3
    ---
          apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
          kind: ProxmoxMachineTemplate
          metadata:
            name: {{ $key }}-worker
            namespace: default
          spec:
            template:
              spec:
                disks:
                  bootVolume:
                    disk: scsi0
                    sizeGb: 20
                format: qcow2
                full: true
                memoryMiB: 4096
                network:
                  default:
                    bridge: vmbr2
                    model: virtio
                numCores: 4
                numSockets: 1
                sourceNode: pve
                templateID: 104
    ---
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          metadata:
            name: {{ $key }}-worker
            namespace: default
          spec:
            template:
              spec:
                joinConfiguration:
                  nodeRegistration:
                    kubeletExtraArgs:
                      provider-id: proxmox://'{{`{{ ds.meta_data.instance_id }}`}}'
                users:
                - name: root
                  sshAuthorizedKeys:
                  - ssh-ed25519 AAAAC
    ---
    {{- end }}
    {{- end }}