---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deploy-capd
  namespace: default
  annotations:
    projectsveltos.io/template: ok
data:
  capd.yaml: |
    {{- if index (getResource "Users") "data" }}
      {{- range $key, $value := (getResource "Users").data }}
        {{- $user := $value | fromYaml }}
          apiVersion: cluster.x-k8s.io/v1beta2
          kind: Cluster
          metadata:
            name: {{ $key }}
            namespace: default
            labels:
              env: {{ $user.env }}
          spec:
            clusterNetwork:
              pods:
                cidrBlocks:
                - 192.168.0.0/16
              serviceDomain: cluster.local
              services:
                cidrBlocks:
                - 10.128.0.0/12
            topology:
              classRef:
                name: quick-start
              controlPlane:
                replicas: 1
              variables:
              - name: imageRepository
                value: ""
              - name: etcdImageTag
                value: ""
              - name: coreDNSImageTag
                value: ""
              - name: podSecurityStandard
                value:
                  audit: restricted
                  enabled: false
                  enforce: baseline
                  warn: restricted
              version: v1.34.3
              workers:
                machineDeployments:
                - class: default-worker
                  name: md-0
                  replicas: 1
    ---
    {{- end }}
    {{- end }}